POST http://localhost:8080/video HTTP/1.1
content-type: application/json

{
    "url": "https://dzone.com/articles/autowiring-spring-beans-into-=classes-not-managed-by-spring"
}

###

GET http://localhost:8080/findall